### ISSUE TITLE
DB setup / .env file

### ISSUE THREAD

**Issue by dgreis** [ebui91/h2go#1]
Hello! Cool repo. I'm interested in adding Google Analytics tracking to it as practice. 

I'm a node/react novice, so not sure if I know exactly what I'm talking about, but would it be possible to commit the DB setup scripts and maybe the DB data too? I tried running the site locally but it doesn't appear to work without some additional setup.

Also, could you maybe add what your `.env` file looks like in the README?

Thanks great work!

**Comment by ebui91** [comment]
Hi David, 

Sorry for the late response, I actually didn't see this issue until just now. I hid my .env file because I didn't want people to have access to some of my private API keys and database config. I'll look into exporting the whole SQL database into a file that you can play around with. I can also DM you the contents of my .env file if you're still interested. Thanks for checking out the repo!

**Comment by ebui91** [comment]
The database was created using postgreSQL. I uploaded them online as .csv files. I used Postico to visualize my tables, but you can use any other software you want. Let me know if there are any other issues, thanks!

You can find out how to import them into SQL here: [http://www.postgresqltutorial.com/import-csv-file-into-posgresql-table/](url) 

Exported table files:
[https://files.fm/u/rempkq55](url)

**Comment by dgreis** [comment]
Thank you Eric. I ended up forking a different repository (https://github.com/dgreis/mock-ecommerce-site) but this is helpful information.
